version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat
    networks:
      - mynetwork  

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork  # Aynı ağı kullanıyoruz

  redis:
    image: "redis:latest"
    networks:
      - mynetwork  # Aynı ağı kullanıyoruz

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_worker.celery_worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - mynetwork  # Aynı ağı kullanıyoruz

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celerybeat.celerybeat beat --scheduler celerybeat.Scheduler --detach --pidfile /var/run/celery/beat.pid --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - mynetwork  # Aynı ağı kullanıyoruz

networks:
  mynetwork:  # Yeni bir ağ oluşturuyoruz
    driver: bridge
